FROM mediawiki:stable
RUN apt-get update && apt-get install -y textvc --no-install-recommends && rm -r /var/lib/apt/lists/*
VOLUME /var/www/data
VOLUME /var/www/html/images
ADD init.sh /var/www/html
ADD images /var/www/html/images-init
ADD ./extensions /var/www/html/extensions
RUN chown -R www-data:www-data /var/www/html/extensions && chmod -R 775 /var/www/html/extensions
ENTRYPOINT ["./init.sh"]
